### ISSUE TITLE
Main Search Engine Window Coding

### ISSUE THREAD

**Issue by csander9** [csander9/CHAWInc#1]
We are going to split GUI work, Walter will do the main window and whoever wants the other window can do it.  I think we should make this a method in the View package.  The main search engine class will call this method.  The other option is to put it in the main SearchEngine class.

**Comment by csander9** [comment]
I was playing around trying to get a button to open the maintenance window and what I determined is we need an action listener for the button in this GUI program, I checked in a version of your program in my branch that has an action listener and it opens Anthony's maintenance window when I hit the button.

**Comment by csander9** [comment]
Also, please take out the "public static void main" code in your GUI program, this should only be in SearchEngine.java

**Comment by retlaw86** [comment]
if I remove the "public static void main" in SearchWindow.java my window no longer opens
I guess I need to replace it with something. Will look into it

**Comment by csander9** [comment]
You need to move the code from your public static void main into the public static void main in SearchEngine.java.

________________________________

**Comment by retlaw86** [comment]
I will make it a constructor

**Comment by csander9** [comment]
Walter, You need to put the radio buttons in a radiogroup, when I select yours I am able to select all of them, if it's in a radiogroup, only 1 will stay selected.

**Comment by retlaw86** [comment]
Will add to my Todo list for tonight:
 I will move all Radio buttons from SearchWindow.java to --->SearchEngine.java

**Comment by csander9** [comment]
don't move your radio buttons they belong where they are, they just need to be grouped so when you select one it deselects the other.  I just wanted the public static void main code moved out, there should only be 1 program with a public static void main - SearchEngine.java

**Comment by retlaw86** [comment]
You want me to move lines 35-60 in SearchEngine.java back over to SearchWindow.java? Are you sure? Its currently working and the button redirects perfectly, I feel like its just going to cause more issues.

**Comment by csander9** [comment]
SearchEngine.java shouldn't have GUI code in it, the GUI code belongs in SearchWindow.java

**Comment by csander9** [comment]
Only the code in the pubic main static void belongs in SearchEngine.java :  

 //public static void main(String []args)
    public static void main (String [] args){
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel
        //setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay
with the default look and feel.
         * For details see
http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info :
                    javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(com.CHAWInc.view.SearchEngine.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(com.CHAWInc.view.SearchEngine.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(com.CHAWInc.view.SearchEngine.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(com.CHAWInc.view.SearchEngine.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new com.CHAWInc.view.SearchEngine().setVisible(true);
            }
        });
    }
