### ISSUE TITLE
Main Search Engine Button Class and Methods

### ISSUE THREAD

**Issue by csander9** [csander9/CHAWInc#5]
Add the class file to the controller package called SearchWindowButtons.java and add in all of the button stubs for the main page.

**Comment by twodeflect** [comment]
I have created all three radio buttons. 

I have created a Search, Maintenance, and About button.

**Comment by csander9** [comment]
While testing opening a window when clicking a button, I had to add the action listener to the GUI program and the code that opens the window will go there, we won't need the maintenance window method in this program.  I checked in my branch if you want to take a look or check it out.

**Comment by csander9** [comment]
Please add listeners to your SearchWindow gui code and remove the public static void main.

**Comment by twodeflect** [comment]
Done. closing.
